/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CONS;

import BUS.ConcessionariaBUS;
import MODELS.Concessionaria;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Claudio
 */
public class FrmConsConcessionaria extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmConsConcessionaria
     *
     * @throws java.lang.Exception
     */
    public FrmConsConcessionaria() throws Exception {
        initComponents();
        this.PreencherTabela();
    }

    ConcessionariaBUS cBus = new ConcessionariaBUS();

    private void PreencherTabela()
            throws Exception {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Código");
        dtm.addColumn("Nome");
        dtm.addColumn("CNPJ");
        dtm.addColumn("Razão Social");
        dtm.addColumn("Endereço");
        dtm.addColumn("Contato");
        dtm.addColumn("Telefone");
        try {
            ArrayList<Concessionaria> lista = cBus.Consultar();
            for (Concessionaria c : lista) {
                dtm.addRow(new String[]{
                    String.valueOf(c.getSEQ_CONCESSIONARIA()),
                    c.getNOM_CONCESSIONARIA(),
                    c.getNUM_CNPJ(),
                    c.getDSC_RAZAO_SOCIAL(),
                    c.getEND_CONCESSIONARIA(),
                    c.getNOM_CONTATO(),
                    c.getNUM_TELEFONE_CONTATO()
                });
            }
            tblResult.setModel(dtm);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    private void PreencherTabela(int SEQ_CONCESSIONARIA)
            throws Exception {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Código");
        dtm.addColumn("Nome");
        dtm.addColumn("CNPJ");
        dtm.addColumn("Razão Social");
        dtm.addColumn("Endereço");
        dtm.addColumn("Contato");
        dtm.addColumn("Telefone");
        try {
            ArrayList<Concessionaria> lista = cBus.ConsultarSeq(SEQ_CONCESSIONARIA);
            for (Concessionaria c : lista) {
                dtm.addRow(new String[]{
                    String.valueOf(c.getSEQ_CONCESSIONARIA()),
                    c.getNOM_CONCESSIONARIA(),
                    c.getNUM_CNPJ(),
                    c.getDSC_RAZAO_SOCIAL(),
                    c.getEND_CONCESSIONARIA(),
                    c.getNOM_CONTATO(),
                    c.getNUM_TELEFONE_CONTATO()
                });
            }
            tblResult.setModel(dtm);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtSeq = new javax.swing.JTextField();
        btnQuery = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();

        setTitle("Consultar Concessionária");

        jLabel3.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel3.setText("Cód. Concessionária:");

        btnQuery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/lupa.png"))); // NOI18N
        btnQuery.setText("Pesquisar");
        btnQuery.setPreferredSize(new java.awt.Dimension(133, 60));
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSeq, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
        if (!txtSeq.getText().isEmpty()) {
            try {
                this.PreencherTabela(Integer.parseInt(txtSeq.getText()));
            } catch (Exception ex) {
                Logger.getLogger(FrmConsAcessorio.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                this.PreencherTabela();
            } catch (Exception ex) {
                Logger.getLogger(FrmConsAcessorio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnQueryActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnQuery;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextField txtSeq;
    // End of variables declaration//GEN-END:variables
}
