/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MDIFORMS;

import BUS.MotorizacaoBUS;
import BUS.TipoMotorizacaoBUS;
import FORM.frmLogin;
import MODELS.Motorizacao;
import MODELS.TipoMotorizacao;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author André
 */
public class FrmCadMotorizacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCadMotorizacao
     *
     * @throws java.lang.Exception
     */
    public FrmCadMotorizacao() throws Exception {
        initComponents();
        this.PreencherTabela();
        this.pCheckMenu();
        this.PreencherCombo();
    }

    MotorizacaoBUS mBus = new MotorizacaoBUS();
    TipoMotorizacaoBUS tmBus = new TipoMotorizacaoBUS();

    private void PreencherTabela()
            throws Exception {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Código");
        dtm.addColumn("Potência");
        dtm.addColumn("Vel. Final");
        dtm.addColumn("Autonomia");
        dtm.addColumn("Descrição");
        dtm.addColumn("Tipo Motorização");
        try {
            ArrayList<Motorizacao> lista = mBus.Consultar();
            for (Motorizacao m : lista) {
                dtm.addRow(new String[]{
                    String.valueOf(m.getSEQ_MOTORIZACAO()),
                    String.valueOf(m.getNUM_POTENCIA()),
                    String.valueOf(m.getNUM_VELOCIDADE_FINAL()),
                    String.valueOf(m.getNUM_AUTONOMIA()),
                    m.getDSC_MOTORIZACAO(),
                    m.getDESC_TIPOMOTORIZACAO()
                });
            }
            tblResult.setModel(dtm);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    private void pCheckMenu() {
        if (frmLogin.PerfUsu != 1) {
            btnCadastrar.setEnabled(false);
            btnAtualizar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }

    private void PreencherCombo() throws ClassNotFoundException {
        DefaultComboBoxModel modelPerfil = new DefaultComboBoxModel();
        ArrayList<TipoMotorizacao> lista = tmBus.Consultar();
        for (TipoMotorizacao tm : lista) {
            modelPerfil.addElement(tm.getDESC_TIPOMOTORIZACAO());
        }
        cboTM.removeAllItems();
        cboTM.setModel(modelPerfil);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSeq = new javax.swing.JTextField();
        txtPot = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        cboTM = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtVF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAut = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cadastrar Motorização");

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Add.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setPreferredSize(new java.awt.Dimension(133, 60));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblResult);

        jLabel3.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel3.setText("Potência:");

        jLabel4.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel4.setText("Nome:");

        txtSeq.setEnabled(false);

        txtPot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPotActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setPreferredSize(new java.awt.Dimension(133, 60));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel5.setText("Tipo Motorização:");

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/edit.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setPreferredSize(new java.awt.Dimension(133, 60));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        cboTM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel2.setText("Código:");

        jLabel6.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel6.setText("Velocidade Final");

        jLabel7.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel7.setText("Autonomia:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSeq, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAut))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPot, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtVF))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboTM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtSeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtPot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtVF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(cboTM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (fc_verif_campos() == 1) {
            int Seq = 0;
            int i = 0;
            try {
                i = tmBus.fc_get_seq(cboTM.getSelectedItem().toString());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmCadMotorizacao.class.getName()).log(Level.SEVERE, null, ex);
            }
            Motorizacao m = new Motorizacao();
            m.setSEQ_MOTORIZACAO(0);
            m.setNUM_POTENCIA(Integer.parseInt(txtPot.getText()));
            m.setNUM_VELOCIDADE_FINAL(Double.parseDouble(txtVF.getText()));
            m.setNUM_AUTONOMIA(Double.parseDouble(txtAut.getText()));
            m.setSEQ_TIPOMOTORIZACAO(i);
            m.setDSC_MOTORIZACAO(txtNome.getText().toUpperCase());
            try {
                Seq = mBus.Incluir(m);
                if (Seq > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Registro: " + Seq + " incluído com sucesso!");
                    this.PreencherTabela();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao incluir");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,
                        ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultMouseClicked
        int a = tblResult.getSelectedRow();
        txtSeq.setText(String.valueOf(tblResult.getValueAt(a, 0)));
        txtPot.setText(String.valueOf(tblResult.getValueAt(a, 1)));
        txtVF.setText(String.valueOf(tblResult.getValueAt(a, 2)));
        txtAut.setText(String.valueOf(tblResult.getValueAt(a, 3)));
        txtNome.setText(String.valueOf(tblResult.getValueAt(a, 4)));
    }//GEN-LAST:event_tblResultMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (!txtSeq.getText().isEmpty()) {
            int Seq = 0;
            if (txtSeq.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Não há registro para excluir.");
            } else {
                try {
                    Seq = mBus.Excluir(Integer.parseInt(txtSeq.getText()));
                    if (Seq > 0) {
                        JOptionPane.showMessageDialog(rootPane, "Registro excluído com sucesso!");
                        this.PreencherTabela();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Erro ao excluir registro.");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,
                            ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Registro para excluir");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        if (fc_verif_campos() == 1) {
            int i = 0;
            try {
                i = tmBus.fc_get_seq(cboTM.getSelectedItem().toString());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmCadMotorizacao.class.getName()).log(Level.SEVERE, null, ex);
            }
            int Seq = 0;
            if (!txtSeq.getText().isEmpty()) {
                Motorizacao m = new Motorizacao();
                m.setSEQ_MOTORIZACAO(Integer.parseInt(txtSeq.getText()));
                m.setNUM_POTENCIA(Integer.parseInt(txtPot.getText()));
                m.setNUM_VELOCIDADE_FINAL(Double.parseDouble(txtVF.getText()));
                m.setNUM_AUTONOMIA(Double.parseDouble(txtAut.getText()));
                m.setSEQ_TIPOMOTORIZACAO(i);
                m.setDSC_MOTORIZACAO(txtNome.getText().toUpperCase());
                try {
                    Seq = mBus.Alterar(m);
                    if (Seq > 0) {
                        JOptionPane.showMessageDialog(rootPane, "Registro alterado com sucesso!");
                        this.PreencherTabela();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Erro ao atualizar.");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,
                            ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Não há registro para atualização.");
            }
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void txtPotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPotActionPerformed

    }//GEN-LAST:event_txtPotActionPerformed

    private int fc_verif_campos() {
        if (txtAut.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Não possui Autonomia. Favor Preecher!");
            return 0;
        }

        if (txtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Não possui Descrição. Favor Preecher!");
            return 0;
        }

        if (txtPot.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Não possui Potência. Favor Preecher!");
            return 0;
        }

        if (txtVF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Não possui Velcidade Final. Favor Preecher!");
            return 0;
        }

        return 1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox cboTM;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextField txtAut;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPot;
    private javax.swing.JTextField txtSeq;
    private javax.swing.JTextField txtVF;
    // End of variables declaration//GEN-END:variables
}
