/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MDIFORMS;

import BUS.PecaBUS;
import BUS.PecaVeiculoBUS;
import BUS.VeiculoBUS;
import FORM.frmLogin;
import MODELS.Peca;
import MODELS.PecaVeiculo;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author André
 */
public class FrmCadPecaVeiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCadPecaVeiculo
     *
     * @throws java.lang.Exception
     */
    public FrmCadPecaVeiculo() throws Exception {
        initComponents();
        this.PreencherTabela();
        this.PreencherComboPeca();
        this.pCheckMenu();
    }

    PecaVeiculoBUS pvBus = new PecaVeiculoBUS();
    VeiculoBUS vBus = new VeiculoBUS();
    PecaBUS pBus = new PecaBUS();

    private void PreencherTabela()
            throws Exception {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Sequêncial");
        dtm.addColumn("Código Peça");
        dtm.addColumn("Código Veículo");
        dtm.addColumn("Nome Peça");
        try {
            ArrayList<PecaVeiculo> lista = pvBus.Consultar();
            for (PecaVeiculo pv : lista) {
                dtm.addRow(new String[]{
                    String.valueOf(pv.getSEQ_PECAVEICULO()),
                    String.valueOf(pv.getSEQ_PECA()),
                    String.valueOf(pv.getSEQ_VEICULO()),
                    pv.getNOM_PECA(),});
            }
            tblResult.setModel(dtm);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    private void pCheckMenu() {
        if (frmLogin.PerfUsu != 1) {
            btnCadastrar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }

    private void PreencherComboPeca() throws ClassNotFoundException {
        DefaultComboBoxModel modelPeca = new DefaultComboBoxModel();
        ArrayList<Peca> lista = pBus.Consultar();
        for (Peca a : lista) {
            modelPeca.addElement(a.getNOM_PECA());
        }
        cboPeca.removeAllItems();
        cboPeca.setModel(modelPeca);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSeq = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        btnCadastrar = new javax.swing.JButton();
        lblSeq = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnQuery = new javax.swing.JButton();
        cboPeca = new javax.swing.JComboBox();
        txtSeqVeiculo = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        lblSeq1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastrar Peças do Veículo");

        txtSeq.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel8.setText("Nome:");

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblResult);

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Add.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setPreferredSize(new java.awt.Dimension(133, 60));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lblSeq.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        lblSeq.setText("Código:");

        jLabel9.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel9.setText("Peça:");

        btnQuery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/lupa.png"))); // NOI18N
        btnQuery.setText("Pesquisar");
        btnQuery.setPreferredSize(new java.awt.Dimension(133, 60));
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });

        cboPeca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setPreferredSize(new java.awt.Dimension(133, 60));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtNome.setEnabled(false);

        lblSeq1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        lblSeq1.setText("Sequêncial");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSeq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSeqVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboPeca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSeq1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSeq))
                            .addComponent(btnQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeq1)
                    .addComponent(txtSeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeq)
                    .addComponent(txtSeqVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultMouseClicked
        int a = tblResult.getSelectedRow();
        txtSeq.setText(String.valueOf(tblResult.getValueAt(a, 0)));
        txtSeqVeiculo.setText(String.valueOf(tblResult.getValueAt(a, 2)));
        int seq = Integer.parseInt(txtSeqVeiculo.getText());
        try {
            txtNome.setText(vBus.ConsultarNome(seq));
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmCadPecaVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblResultMouseClicked

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        int Seq = 0;
        if (!txtSeqVeiculo.getText().isEmpty()) {
            int SeqPca = 0;
            try {
                SeqPca = pBus.fc_get_seq(cboPeca.getSelectedItem().toString());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmCadPecaVeiculo.class.getName()).log(Level.SEVERE, null, ex);
            }

            PecaVeiculo pv = new PecaVeiculo();
            pv.setSEQ_PECAVEICULO(0);
            pv.setSEQ_PECA(SeqPca);
            pv.setSEQ_VEICULO(Integer.parseInt(txtSeqVeiculo.getText()));

            try {
                Seq = pvBus.Incluir(pv);
                if (Seq > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Registro: " + Seq + " incluído com sucesso!");
                    this.PreencherTabela();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao incluir");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,
                        ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Digite um Código de Veículo para Pesquisa.");
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
        if (!txtSeqVeiculo.getText().isEmpty()) {
            int seq = Integer.parseInt(txtSeqVeiculo.getText());
            try {
                txtNome.setText(vBus.ConsultarNome(seq));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmCadPecaVeiculo.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Digite um Código de Veículo para Pesquisa.");
        }
    }//GEN-LAST:event_btnQueryActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (!txtSeq.getText().isEmpty()) {
            int Seq = 0;
            if (txtSeq.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Não há registro para excluir.");
            } else {
                try {
                    Seq = pvBus.Excluir(Integer.parseInt(txtSeq.getText()));
                    if (Seq > 0) {
                        JOptionPane.showMessageDialog(rootPane, "Registro excluído com sucesso!");
                        this.PreencherTabela();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Erro ao excluir registro.");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,
                            ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Registro para excluir");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnQuery;
    private javax.swing.JComboBox cboPeca;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSeq;
    private javax.swing.JLabel lblSeq1;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSeq;
    private javax.swing.JTextField txtSeqVeiculo;
    // End of variables declaration//GEN-END:variables
}
