/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MDIFORMS;

import BUS.FornecedorBUS;
import BUS.PecaBUS;
import FORM.frmLogin;
import MODELS.Fornecedor;
import MODELS.Peca;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Claudio
 */
public class FrmCadPeca extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCadPeca
     *
     * @throws java.lang.Exception
     */
    public FrmCadPeca() throws Exception {
        initComponents();
        this.PreencherTabela();
        this.PreencherComboForn();
        this.pCheckMenu();
        this.PreencherComboPM();
    }

    PecaBUS pBus = new PecaBUS();
    FornecedorBUS fBus = new FornecedorBUS();

    private void PreencherTabela()
            throws Exception {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Código");
        dtm.addColumn("Nome");
        dtm.addColumn("Fornecedor");
        dtm.addColumn("Prod. na Montadora");
        try {
            ArrayList<Peca> lista = pBus.Consultar();
            for (Peca p : lista) {
                dtm.addRow(new String[]{
                    String.valueOf(p.getSEQ_PECA()),
                    p.getNOM_PECA(),
                    p.getNOM_FORNECEDOR(),
                    p.getPROD_MONTADORA()
                });
            }
            tblResult.setModel(dtm);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    private void pCheckMenu() {
        if (frmLogin.PerfUsu != 1) {
            btnCadastrar.setEnabled(false);
            btnAtualizar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }

    private void PreencherComboForn() throws ClassNotFoundException {
        DefaultComboBoxModel modelForn = new DefaultComboBoxModel();
        ArrayList<Fornecedor> lista = fBus.Consultar();
        for (Fornecedor f : lista) {
            modelForn.addElement(f.getNOM_FORNECEDOR());
        }
        cboForn.removeAllItems();
        cboForn.setModel(modelForn);
    }

    private void PreencherComboPM() {
        DefaultComboBoxModel modelCategoria = new DefaultComboBoxModel();
        modelCategoria.addElement("Sim");
        modelCategoria.addElement("Não");
        cboPM.removeAllItems();
        cboPM.setModel(modelCategoria);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtSeq = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        cboForn = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboPM = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("Cadastrar Peça");

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Add.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setPreferredSize(new java.awt.Dimension(133, 60));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblResult);

        jLabel4.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel4.setText("Nome da Peça:");

        txtSeq.setEnabled(false);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setPreferredSize(new java.awt.Dimension(133, 60));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel5.setText("Fornecedor:");

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/edit.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setPreferredSize(new java.awt.Dimension(133, 60));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        cboForn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel2.setText("Código:");

        jLabel3.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel3.setText("Prod. na Montadora:");

        cboPM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSeq, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(9, 9, 9)
                                .addComponent(txtNome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboPM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboForn, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtSeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cboPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (fc_verif_campos() == 1) {
            int Seq = 0;
            int Flg_Prod_Mont = 0;
            if (cboPM.getSelectedItem().toString().equals("Sim")) {
                Flg_Prod_Mont = 1;
            }
            int SeqFor = 0;
            try {
                SeqFor = fBus.fc_get_seq(cboForn.getSelectedItem().toString());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmCadPeca.class.getName()).log(Level.SEVERE, null, ex);
            }
            Peca p = new Peca();
            p.setSEQ_PECA(0);
            p.setNOM_PECA(txtNome.getText().toUpperCase());
            p.setSEQ_FORNECEDOR(SeqFor);
            p.setFLG_PROD_MONT(Flg_Prod_Mont);
            try {
                Seq = pBus.Incluir(p);
                if (Seq > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Registro: " + Seq + " incluído com sucesso!");
                    this.PreencherTabela();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao incluir");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,
                        ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultMouseClicked
        int a = tblResult.getSelectedRow();
        txtSeq.setText(String.valueOf(tblResult.getValueAt(a, 0)));
        txtNome.setText(String.valueOf(tblResult.getValueAt(a, 1)));
        if (String.valueOf(tblResult.getValueAt(a, 3)).equals("Sim")) {
            cboPM.setSelectedIndex(0);
        } else {
            cboPM.setSelectedIndex(1);
        }
    }//GEN-LAST:event_tblResultMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (!txtSeq.getText().isEmpty()) {
            int Seq = 0;
            if (txtSeq.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Não há registro para excluir.");
            } else {
                try {
                    Seq = pBus.Excluir(Integer.parseInt(txtSeq.getText()));
                    if (Seq > 0) {
                        JOptionPane.showMessageDialog(rootPane, "Registro excluído com sucesso!");
                        this.PreencherTabela();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Erro ao excluir registro.");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,
                            ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Registro para excluir");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        if (fc_verif_campos() == 1) {
            int Seq = 0;
            int Flg_Prod_Mont = 0;
            if (cboPM.getSelectedItem().toString().equals("Sim")) {
                Flg_Prod_Mont = 1;
            }
            int SeqFor = 0;
            try {
                SeqFor = fBus.fc_get_seq(cboForn.getSelectedItem().toString());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmCadPeca.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (!txtSeq.getText().isEmpty()) {
                Peca p = new Peca();
                p.setSEQ_PECA(Integer.parseInt(txtSeq.getText()));
                p.setNOM_PECA(txtNome.getText());
                p.setSEQ_FORNECEDOR(SeqFor);
                p.setFLG_PROD_MONT(Flg_Prod_Mont);
                try {
                    Seq = pBus.Alterar(p);
                    if (Seq > 0) {
                        JOptionPane.showMessageDialog(rootPane, "Registro alterado com sucesso!");
                        this.PreencherTabela();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Erro ao atualizar.");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,
                            ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Não há registro para atualização.");
            }
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void cboPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPMActionPerformed

    private int fc_verif_campos() {
        if (txtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Não possui Nome da Peça. Favor Preecher!");
            return 0;
        }
        return 1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox cboForn;
    private javax.swing.JComboBox cboPM;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSeq;
    // End of variables declaration//GEN-END:variables
}
