DROP DATABASE SGA;
CREATE SCHEMA IF NOT EXISTS SGA DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS SGA.ACESSORIO 
(
  SEQ_ACESSORIO INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Chave Primária da Tabela' 
, NOM_ACESSORIO VARCHAR(50) NOT NULL COMMENT 'Nome do Acessório' 
, VAL_ACESSORIO DECIMAL(14, 2) NOT NULL COMMENT 'Valor do veículo'
, USUARIO VARCHAR(30) COMMENT 'Usuário de TimeStamp' 
, DAT_USUARIO DATETIME COMMENT 'Data de TimeStamp' 
, SEQ_MOTORIZACAO INT(11) NOT NULL COMMENT 'Relacionamento com a tabela MOTORIZACAO'
, SEQ_FORNECEDOR INT(11) NOT NULL COMMENT 'Relacionamento com a tabela Fornecedor'
, PRIMARY KEY (SEQ_ACESSORIO))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS SGA.ACESSORIOVEICULO 
(
  SEQ_ACESSORIOVEICULO INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Chave Primária da Tabela' 
, SEQ_ACESSORIO INT(11) NOT NULL COMMENT 'Relacionamento com ACESSORIO' 
, SEQ_VEICULO INT(11) NOT NULL COMMENT 'Relacionamento com VEICULO' 
, USUARIO VARCHAR(30) COMMENT 'Usuário de TimeStamp' 
, DAT_USUARIO DATETIME COMMENT 'Data de TimeStamp' 
, PRIMARY KEY (SEQ_ACESSORIOVEICULO))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS SGA.CONCESSIONARIA 
(
  SEQ_CONCESSIONARIA INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Chave Primária da Tabela' 
, NOM_CONCESSIONARIA VARCHAR(100) COMMENT 'Nome da Concessionária'
, NUM_CNPJ VARCHAR(30) COMMENT 'Número do CNPJ'
, DSC_RAZAO_SOCIAL VARCHAR(50) COMMENT 'Descrição da Razão Social'
, END_CONCESSIONARIA VARCHAR(100) COMMENT 'Endereço da Concessionária'
, NOM_CONTATO VARCHAR(60) COMMENT 'Nome do Contato'
, NUM_TELEFONE_CONTATO VARCHAR(30) COMMENT 'Número de Telefone do Contato'
, USUARIO VARCHAR(30) COMMENT 'Usuário de TimeStamp'
, DAT_USUARIO DATETIME COMMENT 'Data de TimeStamp'
, PRIMARY KEY (SEQ_CONCESSIONARIA))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS SGA.FORNECEDOR 
(
  SEQ_FORNECEDOR INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Chave Primária da Tabela' 
, NOM_FORNECEDOR VARCHAR(100) COMMENT 'Nome do Fornecedor' 
, NOM_FANTASIA VARCHAR(100) COMMENT 'Nome Fantasia' 
, NUM_CNPJ VARCHAR(30) COMMENT 'Número do CNPJ' 
, DSC_RAZAO_SOCIAL VARCHAR(50) COMMENT 'Descrição da Razão Social' 
, END_FORNECEDOR VARCHAR(100) COMMENT 'Endereço do Fornecedor' 
, NOM_CONTATO VARCHAR(60) COMMENT 'Nome do Contato' 
, NUM_TELEFONE_CONTATO VARCHAR(30) COMMENT 'Telefone de Contato' 
, USUARIO VARCHAR(30) COMMENT 'Usuário de TimeStamp' 
, DAT_USUARIO DATETIME COMMENT 'Data de TimeStamp' 
, PRIMARY KEY (SEQ_FORNECEDOR))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS SGA.MOTORIZACAO 
(
  SEQ_MOTORIZACAO INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Chave Primária da Tabela' 
, DSC_MOTORIZACAO VARCHAR(50) NOT NULL COMMENT 'Descrição Padrão da Motorização'
, NUM_POTENCIA INT(11) NOT NULL COMMENT 'Quantidade de Potência (EM HP)' 
, NUM_VELOCIDADE_FINAL DECIMAL(14, 2) NOT NULL COMMENT 'Valor da Velocidade Final (EM KM/H)' 
, NUM_AUTONOMIA DECIMAL(14, 2) NOT NULL COMMENT 'Consumo em litros por tipo de combustível' 
, USUARIO VARCHAR(30) COMMENT 'Usuário de TimeStamp' 
, DAT_USUARIO DATETIME COMMENT 'Data de TimeStamp' 
, SEQ_TIPOMOTORIZACAO INT(11) NOT NULL COMMENT 'Relacionamento com a tabela TIPOMOTORIZACAO'
, PRIMARY KEY (SEQ_MOTORIZACAO))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS SGA.PECA 
(
  SEQ_PECA INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Chave Primária da Tabela' 
, NOM_PECA VARCHAR(50) COMMENT 'Nome da Peça' 
, SEQ_FORNECEDOR INT(11) NOT NULL COMMENT 'Relacionamento com a tabela Fornecedor'
, FLG_PROD_MONT TINYINT DEFAULT 0 NOT NULL COMMENT 'Flag de Produzido pela montadora' 
, USUARIO VARCHAR(30) COMMENT 'Usuário de TimeStamp' 
, DAT_USUARIO DATETIME COMMENT 'Data de TimStamp' 
, PRIMARY KEY (SEQ_PECA))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS SGA.PECAVEICULO 
(
  SEQ_PECAVEICULO INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Chave Primária da Tabela' 
, SEQ_PECA INT(11) NOT NULL COMMENT 'Relacionamento com a tabela PECA'
, SEQ_VEICULO INT(11) NOT NULL COMMENT 'Relacionamento com a tabela VEICULO'
, USUARIO VARCHAR(30) COMMENT 'Usuário de TimeStamp' 
, DAT_USUARIO DATETIME COMMENT 'Data de TimeStamp' 
, PRIMARY KEY (SEQ_PECAVEICULO))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS SGA.TIPOMOTORIZACAO 
(
  SEQ_TIPOMOTORIZACAO INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Chave Primária da Tabela' 
, DESC_TIPOMOTORIZACAO VARCHAR(50) COMMENT 'Descrição do Tipo de Motorização...' 
, USUARIO VARCHAR(30) COMMENT 'Usuário de TimeStamp' 
, DAT_USUARIO DATETIME COMMENT 'Data de TimStamp' 
, PRIMARY KEY (SEQ_TIPOMOTORIZACAO))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS SGA.TIPOVEICULO 
(
  SEQ_TIPOVEICULO INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Chave Primária da Tabela' 
, NOM_TIPOVEICULO VARCHAR(50) COMMENT 'Nome do Veículo' 
, USUARIO VARCHAR(30) COMMENT 'Usuário de TimeStamp' 
, DAT_USUARIO DATETIME COMMENT 'Data de TimStamp' 
, PRIMARY KEY (SEQ_TIPOVEICULO))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS SGA.VEICULO 
(
  SEQ_VEICULO INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Chave Primária da Tabela' 
, NOM_VEICULO VARCHAR(50) NOT NULL COMMENT 'Nome do Veículo' 
, USUARIO VARCHAR(30) COMMENT 'Usuário de TimeStamp' 
, DAT_USUARIO DATETIME COMMENT 'Data de TimeStamp' 
, SEQ_TIPOVEICULO INT(11) NOT NULL COMMENT 'Relacionamento com a Tabela SGA.TIPOVEICULO'
, SEQ_CONCESSIONARIA INT(11) NOT NULL COMMENT 'Relacionamento com a Tabela SGA.CONCESSIONARIA'
, PRIMARY KEY (SEQ_VEICULO))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS SGA.PERFIL 
(
  SEQ_PERFIL INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Chave Primária da Tabela' 
, NOM_PERFIL VARCHAR(50) NOT NULL COMMENT 'Nome do Perfil'
, USUARIO VARCHAR(30) COMMENT 'Usuário de TimeStamp' 
, DAT_USUARIO DATETIME COMMENT 'Data de TimeStamp' 
, PRIMARY KEY (SEQ_PERFIL))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS SGA.USUARIO 
(
  SEQ_USUARIO INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Chave Primária da Tabela' 
, NOM_USUARIO VARCHAR(100) NOT NULL COMMENT 'Nome do Usuário'
, LOGINNAME VARCHAR(30) NOT NULL COMMENT 'LOGINNAME do Usuário'
, USUARIO VARCHAR(30) COMMENT 'Usuário de TimeStamp' 
, DAT_USUARIO DATETIME COMMENT 'Data de TimeStamp' 
, SEQ_PERFIL INT(11) NOT NULL COMMENT 'Relacionamento com a Tabela Perfil'
, PRIMARY KEY (SEQ_USUARIO))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE SGA.ACESSORIOVEICULO ADD CONSTRAINT ACESSORIOVEICULO_UK_001 UNIQUE (SEQ_ACESSORIO, SEQ_VEICULO);
ALTER TABLE SGA.PECAVEICULO ADD CONSTRAINT PECAVEICULO_UK_001 UNIQUE (SEQ_PECA, SEQ_VEICULO);

ALTER TABLE SGA.ACESSORIO ADD CONSTRAINT ACESSORIO_FORNECEDOR_FK FOREIGN KEY (SEQ_FORNECEDOR) REFERENCES SGA.FORNECEDOR (SEQ_FORNECEDOR);
ALTER TABLE SGA.ACESSORIO ADD CONSTRAINT ACESSORIO_MOTORIZACAO_FK FOREIGN KEY (SEQ_MOTORIZACAO) REFERENCES SGA.MOTORIZACAO (SEQ_MOTORIZACAO);
ALTER TABLE SGA.ACESSORIOVEICULO ADD CONSTRAINT ACESSORIOVEICULO_ACESSORIO_FK FOREIGN KEY (SEQ_ACESSORIO) REFERENCES SGA.ACESSORIO (SEQ_ACESSORIO);
ALTER TABLE SGA.ACESSORIOVEICULO ADD CONSTRAINT ACESSORIOVEICULO_VEICULO_FK FOREIGN KEY (SEQ_VEICULO) REFERENCES SGA.VEICULO (SEQ_VEICULO);
ALTER TABLE SGA.MOTORIZACAO ADD CONSTRAINT MOTORIZACAO_TIPOMOTORIZACAO_FK FOREIGN KEY (SEQ_TIPOMOTORIZACAO) REFERENCES SGA.TIPOMOTORIZACAO (SEQ_TIPOMOTORIZACAO);
ALTER TABLE SGA.PECA ADD CONSTRAINT PECA_FORNECEDOR_FK FOREIGN KEY (SEQ_FORNECEDOR) REFERENCES SGA.FORNECEDOR (SEQ_FORNECEDOR);
ALTER TABLE SGA.PECAVEICULO ADD CONSTRAINT PECAVEICULO_PECA_FK FOREIGN KEY (SEQ_PECA) REFERENCES SGA.PECA (SEQ_PECA);
ALTER TABLE SGA.PECAVEICULO ADD CONSTRAINT PECAVEICULO_VEICULO_FK FOREIGN KEY (SEQ_VEICULO) REFERENCES SGA.VEICULO (SEQ_VEICULO);
ALTER TABLE SGA.VEICULO ADD CONSTRAINT VEICULO_CONCESSIONARIA_FK FOREIGN KEY (SEQ_CONCESSIONARIA) REFERENCES SGA.CONCESSIONARIA (SEQ_CONCESSIONARIA);
ALTER TABLE SGA.VEICULO ADD CONSTRAINT VEICULO_TIPOVEICULO_FK FOREIGN KEY (SEQ_TIPOVEICULO) REFERENCES SGA.TIPOVEICULO (SEQ_TIPOVEICULO);
ALTER TABLE SGA.USUARIO ADD CONSTRAINT USUARIO_PERFIL_FK FOREIGN KEY (SEQ_PERFIL) REFERENCES PERFIL (SEQ_PERFIL) ;

ALTER TABLE SGA.ACESSORIO COMMENT 'Para cada modelo, há diversos tipos de configurações possíveis e exclusivas para cada modelo, sendo cada configuração é formada por vários tipos de acessórios e motorização. ';
ALTER TABLE SGA.ACESSORIOVEICULO COMMENT 'Cada tipo de acessório e caracterizado por um código, nome e custo, e diferenciado para cada modelo de carro.';
ALTER TABLE SGA.CONCESSIONARIA COMMENT 'A fabrica só vendem seus veículos para a rede de concessionárias associada à marca, não vendendo diretamente para o usuário final, por isso é necessário saber, a Razão social, CNPJ, endereços, telefones, e os nomes de contato das diversas redes de concessionárias.';
ALTER TABLE SGA.FORNECEDOR COMMENT 'Os fabricantes de peças só produzem peças e os de acessórios só produzem acessórios. As informações relevantes de fornecedores são: Razão social, CNPJ, endereço, telefones e nome de contato.';
ALTER TABLE SGA.MOTORIZACAO COMMENT 'As informações relevantes para a motorização são:  Potencia em HP, velocidade final, autonomia (consumo em litros por tipo de combustível).';
ALTER TABLE SGA.PECA COMMENT 'Muitas das peças que compõem os carros são produzidas por uma rede de fabricantes de peças sendo que para cada tipo de peça pode ser fornecida por mais de um fornecedor.';
ALTER TABLE SGA.PECAVEICULO COMMENT 'Muitas das peças que compõem os carros são produzidas por uma rede de fabricantes de peças sendo que para cada tipo de peça pode ser fornecida por mais de um fornecedor.';
ALTER TABLE SGA.VEICULO COMMENT 'A ACME montadora de carros produz vários modelos de carros de passeio e de transporte leve.';
ALTER TABLE SGA.PERFIL COMMENT 'Tabela de Perfil';
ALTER TABLE SGA.USUARIO COMMENT 'Tabela de Usuários';
